### ISSUE TITLE
ZAP is now Checkmarx

### ISSUE THREAD

**Issue by sydseter** [OWASP/www-project-security-culture#6]
**Describe what change you would like :**

ZAP is now owned by Checkmarx and is in their portfolio, and we should not be seen to endorse one company's products and not another company's products. It is probably easier to remove the section on ZAP

In addition some ZAP features will now become paid-for, which is not truly open source

Context :
Section: https://owasp.org/www-project-security-culture/v10/7-Security_Testing/

see: https://github.com/OWASP/www-project-developer-guide/issues/282

**Comment by nickmillerinfosec** [comment]
Thanks @sydseter . I will remove the reference to ZAP in the next update.

**Comment by sydseter** [comment]
It may have been to rushed from myside. see discussion here: https://github.com/OWASP/www-project-developer-guide/issues/282

**Comment by nickmillerinfosec** [comment]
ok. thanks for the update. we can close this
